name: Auto-Merge
name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - reopened
      - unlocked
jobs:
  automerge:
    runs-on: ubuntu-latest
    # Specifically check that trusted party created this pull-request, and that it has been labelled correctly.
    # if: github.event.pull_request.user.login == 'github-actions' && contains(github.event.pull_request.labels.*.name, 'auto-pr')
    steps:
      - name: automerge
        uses: "DanySK/yaagha@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_FORKS: "false"
          MERGE_LABELS: "auto-pr"
          BLOCK_LABELS: "blocked, wontfix, invalid"
          MERGE_METHOD: "merge"
          CLOSE_ON_CONFLICT: "true"
          DELETE_BRANCH_ON_CLOSE: "true"
          GIT_USER_NAME: "Auto action"
          GIT_USER_EMAIL: "wintvelt@me.com"
