name: Auto-Merge
on:
  pull_request

jobs:
  auto-merge-on-auto-pull:
    runs-on: ubuntu-latest

    # Specifically check that trusted party created this pull-request, and that it has been labelled correctly.
    if: github.event.pull_request.user.login == 'github-actions' && contains(github.event.pull_request.labels.*.name, 'auto-pr')
    steps:
    - uses: alexwilson/enable-github-automerge-action@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"