# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run tests when pushed to dev or master

on: 
  push:
    branches:
      - master
      - dev
    paths-ignore: # if only npm stack-output or package changed, we can ignore this update
      - 'npm/*-stack-output.json'
      - 'npm/package.json'

jobs:
  build:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-central-1
      SECRET_PUBLISH_TOKEN: ${{ secrets.SECRET_PUBLISH_TOKEN }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
        node-version: '16'
        cache: 'npm'
    - name: set env vars
      id: localenv
      run: |
        BRANCH=$(git branch --show-current)
        echo "::set-output name=branch::$BRANCH"
        if [[ $BRANCH == 'master' ]]; then
          echo "we are on MASTER branch"
          echo "STAGE=prod" >> $GITHUB_ENV
        else 
          echo "we are on DEV branch"
          echo "STAGE=dev" >> $GITHUB_ENV
        fi
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
